swagger: "2.0"
info:
  title: Node Js API Project for physiotherapy
  description: API documentation for physiotherapy
  version: "1.0"

host: localhost:8000
schemes:
  - http

consumes:
  - application/json

produces:
  - application/json

paths:
  /api/users/:
    get:
      summary: get all Created users
      description: Returns a list of all patients.
      responses:
        200:
          description: Successful response
          examples:
            application/json:
              users:
                - id: 1
                  name: John Doe
                  email: john@example.com
                  role: user
                - id: 2
                  name: Jane Smith
                  email: jane@example.com
                  role: admin

  /api/admin/patient_registration:
    post:
      summary: Register a new patient
      description: Creates a new patient record
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: patient
          description: Patient registration data
          schema:
            type: object
            properties:
              patientName:
                type: string
              gender:
                type: string
              age:
                type: number
                default: 45
              dob:
                type: string
                format: date
              contact:
                type: number
                default: 123456789
              email:
                type: string
                default: "NA"
              IdProof:
                type: object
                properties:
                  IdType:
                    type: string
                    default: "NA"
                  Id:
                    type: string
                    default: "NA"
              bloodGroup:
                type: string
                default: "NA"
              weight:
                type: number
              height:
                type: number
              relative:
                type: string
                default: "NA"
              complaint:
                type: string
              referredTo:
                type: string
                default: "NA"
              address:
                type: object
                properties:
                  country:
                    type: string
                    default: "India"
                  state:
                    type: string
                  district:
                    type: string
                  pin_code:
                    type: string
                    default: "NA"
                  village:
                    type: string
                    default: "NA"
      responses:
        200:
          description: Successfully registered a new patient
        400:
          description: Bad request, check request payload

  /api/admin/{id}:
    get:
      summary: Get a patient by ID
      parameters:
        - name: id
          in: path
          description: ID of the patient to retrieve
          required: true
          type: string
      responses:
        200:
          description: Successful response
          schema:
            $ref: "#/definitions/Patient"
        404:
          description: Patient not found
          schema:
            type: object
            properties:
              error:
                type: string
    put:
      summary: Update a patient by ID
      parameters:
        - name: id
          in: path
          description: ID of the patient to update
          required: true
          type: string
        - in: body
          name: patient
          description: Patient data to update
          required: true
          schema:
            type: object
            properties:
              patientName:
                type: string
              gender:
                type: string
              age:
                type: number
                default: 45
              dob:
                type: string
                format: date
              contact:
                type: number
                default: 123456789
              email:
                type: string
                default: "NA"
              IdProof:
                type: object
                properties:
                  IdType:
                    type: string
                    default: "NA"
                  Id:
                    type: string
                    default: "NA"
              bloodGroup:
                type: string
                default: "NA"
              weight:
                type: number
              height:
                type: number
              relative:
                type: string
                default: "NA"
              complaint:
                type: string
              referredTo:
                type: string
                default: "NA"
              address:
                type: object
                properties:
                  country:
                    type: string
                    default: "India"
                  state:
                    type: string
                  district:
                    type: string
                  pin_code:
                    type: string
                    default: "NA"
                  village:
                    type: string
                    default: "NA"
      responses:
        200:
          description: Update successful
          schema:
            type: object
            properties:
              status:
                type: string
      responses:
        200:
          description: Update successful
          schema:
            type: object
            properties:
              status:
                type: string
    delete:
      summary: Delete a patient by ID
      parameters:
        - name: id
          in: path
          description: ID of the patient to delete
          required: true
          type: string
      responses:
        200:
          description: Deletion successful
          schema:
            type: object
            properties:
              status:
                type: string
definitions:
  Patient:
    type: object
    properties:
      _id:
        type: string
      firstName:
        type: string
      lastName:
        type: string
